# Generated by Django 4.0 on 2021-12-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('catgy', models.CharField(max_length=200, null=True)),
                ('category', models.TextField(max_length=200, null=True)),
                ('descpshn', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
