# Generated by Django 4.0 on 2021-12-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='catgy',
        ),
        migrations.AlterField(
            model_name='fish',
            name='descpshn',
            field=models.TextField(null=True),
        ),
    ]
