# Generated by Django 4.0 on 2022-01-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
