# Generated by Django 4.0 on 2022-01-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0005_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=200, null=True)),
                ('instshn', models.CharField(max_length=200, null=True)),
                ('ingds', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
